[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # EmailJS Configuration
  VITE_EMAILJS_SERVICE_ID = "service_96vaqcl"
  VITE_EMAILJS_TEMPLATE_ID = "template_l738wmq"
  VITE_EMAILJS_PUBLIC_KEY = "EOx611ifodh1iMCJg"